### ISSUE TITLE
Modification on creating statement of accounts (Manual and Scheduled Generation).

### ISSUE THREAD

**Issue by RoiJS** [RoiJS/Reserbiz#105]
## Overview
This will contains the instructions for modifying the process of creating statement of accounts in connection with the separation of statement of accounts for utility bills and rental bills.

### TODO
- [x] On table **AccountStatements**, introduce new column named **AccountStatementType** (INT NOT NULL) (RentalBiil or UtilityBill). 
- [x] On creating of statement of accounts dialog, update the logic when generating statement of accounts. Introduced new dropdown settings and named it "Statement of Account For:", and this will contain two options, either Rental or Utility.
- [x] Make the Rental as the default option. 
- [x] If the **Rental** fee is selected, redirect to rental bills form page and show the summarize amount for rental bill. Make sure to apply how Miscellaneous Due Date setting works. 
- [x] If it is **Utility**, redirect to utility bills form page and show the summarize amount for utility bill. Utility bill fields (Due date, Electric Bill and Water Bill amount) must be editable. Make sure to apply how Miscellaneous Due Date setting works. 
- [x]  Statement of account generated via the scheduled task, make sure to register it as Rental statement of account.
- [x] Modified Logic on data seeding for creating demo account.
- [x] Test and verify the changes.

**Comment by RoiJS** [comment]
Done implementing following points above. Moving this issue to close now.
