### ISSUE TITLE
Modification on Statement of account list panel.

### ISSUE THREAD

**Issue by RoiJS** [RoiJS/Reserbiz#106]
## Overview
Since there will now be a separate statement of account for rental and utility bills, we have to make some UI enhancement that will indicate if a statement of account is for Rental or for Utility.

### TODO:
- [x]  Add appropriate icon on the statement of account list item which indicates whether the statement of account is for Rental or Utility.
- [x] On filter dialog, introduce new filter setting that will sort the list based on the Statement of Account type (Rental or Utility).
- [x] Update the logic of paid status. Based it on the actual payment status.
- [x] Test and verify.

**Comment by RoiJS** [comment]
Done implementing the following points above. Moving this ticket to close now.
