### ISSUE TITLE
Modification on Sending Statement of account details via SMS and Email.

### ISSUE THREAD

**Issue by RoiJS** [RoiJS/Reserbiz#108]
## TODO:
- [x] If the statement of account is for Rental, make sure to only send details related with the Rental bills.
- [x] If the statement of account is for Utility, make sure to only send details related with the Utility bills.
- [x] Test and verify.

**Comment by RoiJS** [comment]
Following above points are now implemented. Moving this ticket to close now.
