### ISSUE TITLE
Modification on Payment list page

### ISSUE THREAD

**Issue by RoiJS** [RoiJS/Reserbiz#109]
### TODO:
- [x] For register payment dialog, If the statement of account is for Rental, on Payment For dropdown settings, only show options that is related with Rental. (Rental, Penalty and/or Miscellaneous - Still depends on the Miscellaneous due date setting).
- [x] For filter payment dialog, If the statement of account is for Rental, on Payment For dropdown settings, only show options that is related with Rental. (All, Rental, Penalty and/or Miscellaneous - Still depends on the Miscellaneous due date setting).
- [x] For register payment dialog, If the statement of account is for Utility, on Payment For dropdown settings, only show options that are related with Utility (Electric, Water and/or Miscellaneous - Still depends on the Miscellaneous due date setting).
- [x] For register filter dialog, If the statement of account is for Utility, on Payment For dropdown settings, only show options that are related with Utility (All, Electric, Water and/or Miscellaneous - Still depends on the Miscellaneous due date setting).
- [x] Test and verify.

**Comment by RoiJS** [comment]
Done implementing following points above. Moving this ticket to close now.
