### ISSUE TITLE
Term Details: Introduce auto-send generated statement of account setting

### ISSUE THREAD

**Issue by RoiJS** [RoiJS/Reserbiz#113]
## Overview

The goal of this ticket is to give admin the option to auto-send a new statement of accounts that are generated by the scheduled task. Basically, this will follow the same  logic on how we currently sending statement of account from within the statement of account details page by clicking the **Send Details** button.

### TODO
- [x]  On term page, under Automation Settings form group, add new setting called **Auto-send Statement of Account**. Make sure to apply this new setting on Add, Edit Term pages and also on the Contract details term page.
- [x] On the scheduled task, add a logic to automatically send statement of account details. Make sure to follow the same logic when manually sending statement of account details. 
- [x] On Statement of account details page, add a section to display last date time sent.
- [x] Update online documentation.

**Comment by RoiJS** [comment]
Done implementing the following points above. Moving this ticket to close now.
