### ISSUE TITLE
Contract Details Page: Introduce settings to control how the paid status is validated for statement of accounts 

### ISSUE THREAD

**Issue by RoiJS** [RoiJS/ReSerBiz#67]
### Overview
Currently, the statement of accounts is marked as paid if the total amount for statement of accounts is already paid by the tenant. This total amount comprises the rental, utility bills, miscellaneous and penalties and all of these must be paid before the statement of account is considered as paid. This functionality could be a problem in the future because we might never know how the user would want the calculation for paid status would be. With this, I decided to introduce settings so user can customize in someway how the statement of account will be considered as paid.

On Contract Details page, we introduced two new section, (1) General Information  and  (2) Mark Account Statement as Paid sections.

**General Information Section** will have the current available fields on the contract details page.

### TODO
For **Mark Account Statement as Paid** section on the other hand, introduce the following new settings:

- [x] Check Rental Amount
- [x] Check Utility Bills
- [x] Check Miscellaneous Fees
- [x] Check Penalties
- [x] Update the logic which identifies if the statement of account is paid or unpaid
- [x] Display the breakdown payment on statement of accounts details page
- [x] Update manual adding of statement of account when **Mark as Paid** setting is true
- [x] Update Dataseeding of statement of accounts payment details

Update also the following:
- [x] Unit Test
- [x] Online Documentation

**Comment by RoiJS** [comment]
This issue has been implemented. Moving this issue to close now.
