### ISSUE TITLE
Register Payment: Improvement on pre-filling values for amount if the Amount For Deposit setting is activated.

### ISSUE THREAD

**Issue by roam9152** [RoiJS/Reserbiz#69]
### Overview
Currently, the system has the functionality to pre-fill amount field when registering payment. The amount field is pre-fill when the setting **Amount From Deposit** setting is activated. The pre-filled amount is based on the contract rate or the remaining unused deposited amount for the contract. If the contract rate is less than the remaining deposited amount then the contract rate will be the prefilled amount, otherwise the remaining deposited amount is used.

Now on issue #66, we introduced a new setting on the payment register dialog that identifies the **Payment For Type** (Rental, Electric Bill, Water Bill, Miscellaneous Fees or Penalty) for the payment. For a better user experience, we also make the pre-filled value be based on the selected **Payment For type** setting. Example, if the setting is "Electric Bill" then the suggested pre-filled value will be the Electric bill amount of the current statement of account. The same concept for other **Payment For Type**.

### TODO
- [x] Make the suggested prefill amount value based on the **Payment For Type** settings.
- [x] Update the Unit Test
- [x] Update the Online Documentation
