### ISSUE TITLE
Statement of account Details Page: Hide Utility Bills details if both Electric and Water Bill is set to be included on the Rate

### ISSUE THREAD

**Issue by RoiJS** [RoiJS/Reserbiz#73]
On statement of account details, user can specify the amount for electric and water bills. This is possible whether the electric or water bill amount is excluded from the rate or not, which is configured on terms details.

I guess, its better to hide these fields if the electric or water bill amount is already included on the rate.

The goal of this issue is to hide the electric or water bill amount fields if they are already included on the rate.

**TODO:**
- [x] Hide electric bill amount field if it is set to be included on rental rate
- [x] Hide water bill amount field if it is set to be included on rental rate.
- [x] If both are set to be included on the rental rate then hide the entire section.
- [x] Update the format when sending statement of accounts via email and SMS.
- [x] Update Online Documentation

**Comment by RoiJS** [comment]
Done implementing this issue. Moving this issue to close now.
