### ISSUE TITLE
Make the database server, username and password dynamic on database connection string template

### ISSUE THREAD

**Issue by RoiJS** [RoiJS/Reserbiz#92]
I just found out the the database server offered by the hosting server is changing and this causes a problem on the connection string template declared on the app settings file on the web api as it statically provide the server, username and password for the connection string except for the database name which is dynamic.

To resolve this issue, we will make the server, username and password dynamic as well.

**TODO:**
- [x] Introduced new columns DBServer, DBUsername and DBPassword on table Clients.
- [x] Introduce new settings on the appSettings.Development.json and appSettings.Production.json which contains the default server, username and password that the system will use when registering new database.
- [x] Update the connection string template on the appSettings.json
- [x] Modify Startup.cs. Provide the server, username and password dynamically on the current connection string for every request.
- [x] Modify the function that registers client and demo databases
- [x] Test and verify
