### ISSUE TITLE
Introduce Notifications page

### ISSUE THREAD

**Issue by RoiJS** [RoiJS/Reserbiz#95]
On issue #34 and #35 we have implemented the push notification feature on Reserbiz. This feature is only used whenever there is a new statement of account generated. There is something that we can enhanced on this feature and this is to persist these notifications so user can see the list of notifications (read and unread notifications).

This issue is focus on introducing new page on the app where list of notifications are shown. 

**TODO:**
- [x] Introduce new table and back-end code that will manage the list of notifications.
- [x] Update the logic when auto generating statement of accounts. Add logic that will store information related to the notifications. Details like, Message, date and time, account id, read or unread status. and the notification path.
- [x] Introduce new notifications page. This page contains the list of notifications.
- [x] Sort the list based on date and time descending order.
- [x] Introduced advanced filter dialog. Add date and time and also sort order filter settings.
- [x] When clicking an item, make sure to redirect the user to the page corresponds to the notifications and automatically marked the notification item as read.
- [x] Test and verify.
- [x] Make sure to update the Unit test if there are things that needs to be updated
- [x] Make sure to add this new feature on Reserbiz Online Documentation.

**Development Environment:**
**Branch:** Features/95-Introduce-Notifications-page
**Database:** db_a727c0_demo52

**Comment by RoiJS** [comment]
Done working on the following tasks above. Moving this ticket to close now.
